services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas
    ports:
      - "5432:5432"
    volumes:
      - saas_pgdata:/var/lib/postgresql/data
      - ../infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro


  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    container_name: saas_dev
    depends_on:
      - db
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity

volumes:
  saas_pgdata:
